apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-mongo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JJ-Anyasi/devops-full-project.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true